---
title: "Pillar 1 - Student Topic Profile"
author: "DARS"
date: "`r Sys.Date()`"
knit: (function(inputFile, encoding) { 
      out_dir <- 'rm files';
      rmarkdown::render(inputFile,
                        encoding=encoding, 
                        output_file=file.path(dirname(inputFile), out_dir, 'Useful Functions.md')) })
output: 
  github_document:
    toc: TRUE
editor_options: 
  chunk_output_type: console
---



# Helper Functions

```{r}
collapse_or       <- function(string) string %>% str_c(collapse = "|")
collapse_space    <- function(string) string %>% str_c(collapse = " ")
```

```{r}
find_df <- function(course)  d_student_model %>% filter(`Course ID` == course)
```


```{r} 
my_cv.glmnet <- function(df, alpha = 1, predictors){
  
  df <- df %>% select(Grade, matches(predictors))
  
  y <- df %>% select(Grade             ) %>% as.matrix
  x <- df %>% select(matches(predictors)) %>% as.matrix
  
  nfold <- min(10, floor(nrow(df) / 3))
  
  cv.glmnet(x, y, nfolds = nfold, type.measure = "mae", alpha = alpha)
  
}
```


# Save

```{r}
save(list = ls(), file = "Output/useful functions.RDATA")
```
